/** Self-contained MCP Apps resource. No CDN, AI SDK, cookies, or local library access.
 * Uses the standard JSON-RPC postMessage bridge; no host-name-specific branching.
 * Semantic colors and motion match src/design/tokens.css (checked in flowUi.test.ts).
 */
export const FLOW_UI_URI = "ui://precipice/flow-preview.html";
export const FLOW_UI_MIME = "text/html;profile=mcp-app";
export const FLOW_UI_HTML = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Precipice flow preview</title><style>
:root { color-scheme:light; --bg-base:#f7f5f1; --bg-surface:#fcfbf9; --bg-raised:#ffffff; --bg-canvas:#f0ede7; --text-primary:#1e1b17; --text-secondary:#5a5248; --border-default:rgba(30,27,23,.1); --action-primary:#b02f06; --text-on-action-primary:#ffffff; --obj-note:#8a6a3d; --obj-journey:#4e8c86; --obj-wireframe:#5b6bae; --obj-scape:#a85f5a; --danger:#c33a2e; --r-lg:12px; --r-md:8px; --space-1:4px; --space-2:8px; --space-3:12px; --space-4:16px; --space-6:24px; --dur-fast:130ms; --ease-out:cubic-bezier(.16,1,.3,1); --font-ui:ui-sans-serif,system-ui,sans-serif; }
:root.dark { color-scheme:dark; --bg-base:#191613; --bg-surface:#221e1a; --bg-raised:#2b2721; --bg-canvas:#141210; --text-primary:#ede9e1; --text-secondary:#a79e92; --border-default:rgba(237,233,225,.12); --obj-note:#c6a268; --obj-journey:#6fb3ac; --obj-wireframe:#8794d4; --obj-scape:#c98a85; --action-primary:#ff7033; --text-on-action-primary:#ffffff; --danger:#f07a6d; }
*{box-sizing:border-box} body{margin:0;font:14px/1.5 var(--font-ui);background:var(--bg-surface);color:var(--text-primary)}
main{padding:var(--space-4);max-width:1000px;margin:auto} header,.actions,.navigation{display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap} header{justify-content:space-between} h1{font-size:18px;margin:0} h2{font-size:16px;margin:0 0 var(--space-3)} p{margin:var(--space-2) 0} .muted,.type{color:var(--text-secondary)} .type{font-size:12px;text-transform:uppercase;letter-spacing:.04em} .badge{padding:var(--space-1) var(--space-2);border:1px solid var(--border-default);border-radius:var(--r-md);font-size:12px}
button,select,textarea,input{font:inherit;color:inherit} button,select{background:var(--bg-raised);border:1px solid var(--border-default);border-radius:var(--r-md);padding:var(--space-2) var(--space-3)} button{cursor:pointer;transition:transform var(--dur-fast) var(--ease-out)} button:active{transform:scale(.98)} button:disabled{cursor:default;opacity:.5} button:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--action-primary);outline-offset:2px} .primary{background:var(--action-primary);color:var(--text-on-action-primary)}
.map{overflow:auto;border:1px solid var(--border-default);border-radius:var(--r-lg);background:var(--bg-canvas);margin:var(--space-4) 0;max-height:300px} svg{display:block} .map text{fill:var(--text-primary);font:14px var(--font-ui)} .node rect{fill:var(--bg-raised);stroke:var(--border-default);stroke-width:2} .node[aria-pressed=true] rect{stroke:var(--action-primary);stroke-width:3} .node{cursor:pointer} .node:focus{outline:none} .node:focus-visible rect{stroke:var(--action-primary);stroke-width:4} .edge{stroke:var(--text-secondary);stroke-width:1.5;fill:none} .navigation{margin-bottom:var(--space-3)} select{min-width:0;max-width:100%;flex:1} article{border:1px solid var(--border-default);border-radius:var(--r-lg);padding:var(--space-4);background:var(--bg-raised);max-height:320px;overflow:auto} .prose{white-space:pre-wrap;overflow-wrap:anywhere} ol{padding-left:var(--space-6);margin:0} li{margin:0 0 var(--space-3)} li p{color:var(--text-secondary)} .connections{font-size:12px;color:var(--text-secondary);margin-top:var(--space-3)} .wireframe{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:var(--space-2)} .primitive{padding:var(--space-2);border:1px solid var(--border-default);border-radius:var(--r-md);overflow-wrap:anywhere} .primitive.section,.primitive.heading{font-weight:600} .primitive.section{border:0;padding-top:var(--space-4)} .primitive.divider{border:0;border-top:1px solid var(--border-default)} .primitive.button{background:var(--bg-base);text-align:center} .primitive.image,.primitive.box{min-height:64px;background:var(--bg-canvas);display:grid;place-items:center} .primitive.text,.primitive.heading{border:0} footer{border-top:1px solid var(--border-default);padding-top:var(--space-4);margin-top:var(--space-4)} #status{min-height:21px;overflow-wrap:anywhere} #status.error{color:var(--danger)} #sharing{margin-top:var(--space-3);padding:var(--space-3);border:1px solid var(--border-default);border-radius:var(--r-md)} textarea{width:100%;resize:vertical;background:var(--bg-base);border:1px solid var(--border-default);border-radius:var(--r-md);padding:var(--space-2);font-size:12px} a{color:var(--text-primary);overflow-wrap:anywhere} [hidden]{display:none!important}
@media(hover:hover) and (pointer:fine){button:not(:disabled):hover{filter:brightness(.97)}} @media(prefers-reduced-motion:reduce){button{transition:none}button:active{transform:none}} @media(max-width:420px){main{padding:var(--space-3)}.actions button{flex:1} .map{max-height:220px}}
</style></head><body><main>
<header><div><div class="type">Precipice</div><h1 id="name">Flow preview</h1></div><span class="badge" id="badge">Draft · not saved</span></header>
<p class="muted" id="summary">Preparing your preview…</p>
<div class="map" id="map" aria-label="Flow map"></div>
<div class="navigation"><button id="previous" aria-label="Previous block">←</button><select id="objects" aria-label="Inspect a block"></select><button id="next" aria-label="Next block">→</button></div>
<article id="detail" aria-label="Selected block"></article>
<footer><p id="status" role="status" aria-live="polite">You can inspect every block before creating it.</p>
<div class="actions"><button id="create" class="primary" disabled>Create in Precipice</button><button id="discard" disabled>Discard</button><button id="share" disabled>Share preview</button><button id="refresh">Refresh status</button></div>
<p class="muted" id="expiry"></p>
<div id="sharing" hidden><p id="disclosure">Anyone with the link will be able to view the entire preview, including all notes and screens. This uses a published snapshot slot and stays shared until you withdraw it.</p><button id="publish" class="primary">Make preview public</button><button id="close-share">Cancel</button><div id="links" hidden><p><a id="url" target="_blank" rel="noopener noreferrer">Open shared preview</a></p><label for="embed">Iframe embed code</label><textarea id="embed" rows="3" readonly></textarea><button id="copy">Copy iframe code</button><button id="withdraw">Withdraw shared preview</button></div></div>
</footer></main><script>
(function(){
  'use strict';
  var el=function(id){return document.getElementById(id)}, seq=0, pending=new Map(), ready=false, data=null, meta=null, index=0, busy=false, terminal=false, shared=null, expiryTimer;
  var notify=function(method,params){window.parent.postMessage({jsonrpc:'2.0',method:method,params:params},'*')};
  function request(method,params){return new Promise(function(resolve,reject){var id=++seq;var timer=setTimeout(function(){pending.delete(id);reject(new Error('Precipice did not answer. Check the creation status before retrying.'))},30000);pending.set(id,{resolve:resolve,reject:reject,timer:timer});window.parent.postMessage({jsonrpc:'2.0',id:id,method:method,params:params},'*')})}
  function status(text,error){el('status').textContent=text;el('status').classList.toggle('error',!!error)}
  function controls(){var expired=meta&&Date.now()>=meta.expires_at;el('create').disabled=!ready||busy||terminal||expired||!meta||!meta.can_write;el('discard').disabled=el('create').disabled;el('share').disabled=!ready||busy||expired||!meta||!meta.can_write||data.status==='cancelled';el('publish').disabled=el('share').disabled;el('withdraw').disabled=!ready||busy||!shared;el('refresh').disabled=!ready||busy||!data;if(expired&&!terminal){el('badge').textContent='Preview expired';status('Ask for a fresh preview to create this flow.')}}
  function call(name,args){return request('tools/call',{name:name,arguments:args})}
  function outcome(result){if(result.structuredContent)return result.structuredContent;var text=(result.content||[]).find(function(c){return c.type==='text'});return text?JSON.parse(text.text):{status:'failed',message:'No creation receipt was returned.'}}
  function auth(){return {scape_id:data.scape_id,preview_id:data.operation_id,confirmation_token:meta.confirmation_token}}
  function theme(ctx){if(ctx&&ctx.theme)document.documentElement.classList.toggle('dark',ctx.theme==='dark')}
  function node(tag,text,cls){var n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
  function detail(){var o=meta.preview.objects[index];el('detail').replaceChildren();if(!o){el('detail').append(node('p','This flow has no blocks.'));return}el('objects').value=String(index);el('previous').disabled=index===0;el('next').disabled=index===meta.preview.objects.length-1;el('detail').append(node('div',o.type,'type'),node('h2',o.title||'Untitled'));
    if(o.type==='journey'){var list=node('ol');(o.data.steps||[]).forEach(function(s){var li=node('li');li.append(node('strong',s.label));if(s.detail)li.append(node('p',s.detail));list.append(li)});el('detail').append(list)}
    else if(o.type==='wireframe'){var grid=node('div',undefined,'wireframe'),columns=o.data.columns||12;grid.style.gridTemplateColumns='repeat('+columns+',minmax(0,1fr))';(o.data.primitives||[]).forEach(function(p){var labels={image:'Image',avatar:'Avatar',input:'Input',checkbox:'☐',toggle:'Toggle',divider:''};var n=node('div',p.label===undefined?(labels[p.kind]===undefined?p.kind:labels[p.kind]):p.label,'primitive '+p.kind);n.style.gridColumn='span '+(p.kind==='section'?columns:Math.min(p.span,columns));if(p.align)n.style.textAlign=p.align;if(p.size&&['box','image','avatar'].includes(p.kind))n.style.minHeight=({sm:40,md:64,lg:96})[p.size]+'px';grid.append(n)});el('detail').append(grid)}
    else el('detail').append(node('div',o.data.body||'','prose'));
    var edges=meta.preview.relationships.filter(function(r){return r.from===o.id||r.to===o.id});if(edges.length){var names=new Map(meta.preview.objects.map(function(o){return [o.id,o.title||o.id]}));var c=node('div',undefined,'connections');edges.forEach(function(r){c.append(node('p',(names.get(r.from)||r.from)+' → '+(names.get(r.to)||r.to)+(r.label?' · '+r.label:'')))});el('detail').append(c)}
    document.querySelectorAll('.node').forEach(function(n){n.setAttribute('aria-pressed',String(n.dataset.index===String(index)))})
  }
  function map(){var objects=meta.preview.objects,ns='http://www.w3.org/2000/svg';function svgNode(tag,attrs,text){var n=document.createElementNS(ns,tag);Object.entries(attrs||{}).forEach(function(a){n.setAttribute(a[0],a[1])});if(text!==undefined)n.textContent=text;return n}var svg=svgNode('svg',{'aria-label':'Connected flow blocks'}),positions=new Map();var minX=Math.min(0,...objects.map(function(o){return o.x})),minY=Math.min(0,...objects.map(function(o){return o.y})),maxX=600,maxY=180;objects.forEach(function(o){var x=o.x-minX+24,y=o.y-minY+24;positions.set(o.id,{x:x,y:y});maxX=Math.max(maxX,x+244);maxY=Math.max(maxY,y+100)});svg.setAttribute('viewBox','0 0 '+maxX+' '+maxY);svg.style.width=Math.max(600,maxX*.65)+'px';svg.style.height=Math.max(180,maxY*.65)+'px';
    meta.preview.relationships.forEach(function(r){var a=positions.get(r.from),b=positions.get(r.to);if(!a||!b)return;var x=a.x+220,y=a.y+36;svg.append(svgNode('path',{d:'M '+x+' '+y+' C '+(x+40)+' '+y+', '+(b.x-40)+' '+(b.y+36)+', '+b.x+' '+(b.y+36),class:'edge'}));svg.append(svgNode('text',{x:b.x-16,y:b.y+41},'›'))});
    objects.forEach(function(o,i){var p=positions.get(o.id),g=svgNode('g',{class:'node',tabindex:'0',role:'button','aria-label':o.title||o.id,'aria-pressed':String(i===index),'data-index':String(i),transform:'translate('+p.x+' '+p.y+')'});g.append(svgNode('rect',{width:220,height:72,rx:8}),svgNode('text',{x:12,y:24},o.type),svgNode('text',{x:12,y:49},(o.title||'Untitled').slice(0,25)));var select=function(){index=i;detail()};g.addEventListener('click',select);g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}});svg.append(g)});el('map').replaceChildren(svg)
  }
  function resetShare(){shared=null;el('links').hidden=true;el('publish').hidden=false;el('close-share').textContent='Cancel';el('url').removeAttribute('href');el('embed').value=''}
  function receive(result){var next=outcome(result);if(next.status!=='preview'){status(next.message||'The preview could not be prepared.',true);return}if(!result._meta||!result._meta.preview){status('This client did not deliver the preview. Use Precipice’s in-app review.',true);return}data=next;meta=result._meta;terminal=false;index=0;resetShare();el('sharing').hidden=true;el('badge').textContent='Draft · not saved';status('You can inspect every block before creating it.');el('name').textContent=meta.preview.name;el('summary').textContent=meta.preview.objects.length+' blocks · '+meta.preview.relationships.length+' connections · '+(meta.preview.target==='new'?'New scape':'Changes to an existing scape')+'. '+next.message;el('objects').replaceChildren(...meta.preview.objects.map(function(o,i){var n=node('option',o.title||'Untitled');n.value=String(i);return n}));map();detail();el('create').textContent=meta.preview.target==='new'?'Create in Precipice':'Apply in Precipice';el('expiry').textContent='Creation preview expires at '+new Date(meta.expires_at).toLocaleTimeString()+'. Shared links remain available until withdrawn.';if(!meta.can_write)status('This connection is read-only. Reconnect with edit access to create or share.');clearTimeout(expiryTimer);expiryTimer=setTimeout(controls,Math.max(0,meta.expires_at-Date.now()));controls()}
  window.addEventListener('message',function(e){if(e.source!==window.parent||!e.data||e.data.jsonrpc!=='2.0')return;var m=e.data;if(m.id!==undefined&&pending.has(m.id)){var p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);if(m.error)p.reject(new Error(m.error.message));else p.resolve(m.result);return}if(m.method==='ui/notifications/tool-result')receive(m.params);else if(m.method==='ui/notifications/host-context-changed')theme(m.params);else if(m.method==='ui/notifications/tool-cancelled'){terminal=true;if(data)data.status='cancelled';el('badge').textContent='Cancelled';controls();status('Preview cancelled. Ask for a fresh preview.');}else if(m.method==='ui/resource-teardown'){ready=false;controls();clearTimeout(expiryTimer);pending.forEach(function(p){clearTimeout(p.timer);p.reject(new Error('Preview closed'))});pending.clear();window.parent.postMessage({jsonrpc:'2.0',id:m.id,result:{}},'*')}});
  el('objects').onchange=function(){index=Number(this.value);detail()};el('previous').onclick=function(){if(index>0){index--;detail()}};el('next').onclick=function(){if(index<meta.preview.objects.length-1){index++;detail()}};
  async function confirm(approve){if(busy||!data||terminal)return;busy=true;controls();status(approve?'Creating in Precipice…':'Discarding preview…');try{var r=outcome(await call('confirm_flow',Object.assign(auth(),{approve:approve})));if(r.status==='applied'||r.status==='cancelled'){terminal=true;data.status=r.status;el('badge').textContent=r.status==='applied'?(meta.preview.target==='new'?'Created in Precipice':'Applied in Precipice'):'Discarded';el('create').textContent=el('badge').textContent;status(r.status==='applied'?'Saved in Precipice. '+r.message:r.message)}else{status(r.message||'Creation was not confirmed.',true)}}catch(e){status(e.message,true);el('refresh').hidden=false}finally{busy=false;controls()}}
  el('create').onclick=function(){confirm(true)};el('discard').onclick=function(){confirm(false)};
  el('refresh').onclick=async function(){if(busy||!ready||!data)return;busy=true;controls();try{var result=await call('get_operation',{operation_id:data.operation_id}),r=outcome(result);if(r.status==='applied'||r.status==='cancelled'){terminal=true;data.status=r.status;el('badge').textContent=r.status==='applied'?(meta.preview.target==='new'?'Created in Precipice':'Applied in Precipice'):'Discarded'}if(result._meta&&'share' in result._meta){if(result._meta.share){showShare(result._meta.share);el('sharing').hidden=false}else resetShare()}status(r.status==='preview'?'The flow has not been created. You can retry creation.':r.message||r.status,r.status==='failed')}catch(e){status(e.message,true)}finally{busy=false;controls()}};
  el('share').onclick=function(){el('sharing').hidden=false};el('close-share').onclick=function(){el('sharing').hidden=true};
  function showShare(r){shared=r;el('links').hidden=false;el('publish').hidden=true;el('close-share').textContent='Done';var u=new URL(r.url);if(u.protocol!=='https:')throw new Error('Invalid share link.');el('url').href=u.href;el('embed').value=r.iframe}
  async function share(withdraw){if(busy||!ready||!data)return;busy=true;controls();status(withdraw?'Withdrawing shared preview…':'Sharing preview…');try{var r=outcome(await call('share_flow_preview',Object.assign(auth(),{withdraw:withdraw})));if(r.status==='failed')throw new Error(r.message);if(withdraw)resetShare();else showShare(r);status(r.message)}catch(e){status(e.message,true)}finally{busy=false;controls()}}
  el('publish').onclick=function(){share(false)};el('withdraw').onclick=function(){share(true)};el('copy').onclick=async function(){try{await navigator.clipboard.writeText(el('embed').value);status('Iframe code copied.')}catch(e){el('embed').focus();el('embed').select();status('Select and copy the iframe code above.')}};
  if(window.parent===window){status('Open this preview from the Precipice connector in chat. For website embeds, use a shared preview link.');return}
  request('ui/initialize',{appInfo:{name:'Precipice flow preview',version:'1.0.0'},appCapabilities:{availableDisplayModes:['inline']},protocolVersion:'2026-01-26'}).then(function(r){ready=!!(r.hostCapabilities&&r.hostCapabilities.serverTools);theme(r.hostContext);notify('ui/notifications/initialized',{});controls();if(!ready)status('This host cannot create flows from the preview. Use Precipice’s in-app review.');if(typeof ResizeObserver!=='undefined')new ResizeObserver(function(){notify('ui/notifications/size-changed',{height:document.body.scrollHeight})}).observe(document.body)}).catch(function(e){status('Could not connect the preview to chat. Use Precipice’s in-app review.',true)});
})();
</script></body></html>`;
